name: Github actions to aws oidc check

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  oidc-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials from OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::448049797837:role/githubActions
          aws-region: ap-south-1

      - name: Verify AWS credentials
        run: |
          aws sts get-caller-identity
